### PR TITLE
Polynomial Tree Class implementation

### PR DESCRIPTION
**Pull request by barneyhill**
Includes sphinx documentation, testing and limited functionality. Over the next month more advanced methods and splitting algorithms will be implemented. Overview of current functionality is avaliable at https://discourse.effective-quadratures.org/t/polynomials-trees-structure-and-splitting/60

### CODE REVIEW

**Comment by ascillitoe** [comment]
For the initial commit this looks good to me! @psesh and @ncywong, any thoughts before we merge?

**Comment by barneyhill** [comment]
Oops could've sworn I'd removed that.

**Comment by psesh** [comment]
This looks great @barneyhill! Just one minor request: Can you delete the effective-quadratures-output.txt file please?

**Comment by discourse-eq** [comment]
This pull request has been mentioned on **Effective Quadratures**. There might be relevant details there:

https://discourse.effective-quadratures.org/t/google-summer-of-code-review-implementing-polynomial-regression-trees-in-effective-quadratures/74/1

**Pull request merged**
