### PR TITLE
Default values added for Parameter. Closes #216

### LINKED ISSUE #216: Improvements to Parameter
Parameter should have a default `uniform` distribution and a default `order` of 1.

```
p = Parameter(lower=-1., upper=1.)
# TypeError: __init__() missing 2 required positional arguments: 'order' and 'distribution'
```

Parameter should take in a name in its constructor. If a name is not provided a default value of `'parameter'` can be assigned.

`horsepower = Parameter(name='horsepower', lower=180, upper=350)`

### PR DESCRIPTION
**Pull request by PrayasJ**

### CODE REVIEW

**Comment by psesh** [comment]
This is great @PrayasJ ! Well done! May I trouble you to update `test_parameter.py` to ensure that you are testing your new functionality please?

**Comment by PrayasJ** [comment]
Sure but I couldn't find `test_parameter.py` within the tests folder, should I create it?

**Comment by psesh** [comment]
Yes please :) Cheers!

**Comment by PrayasJ** [comment]
Done.

**Pull request merged**
