### PR TITLE
Final GSoC PolyTree Pull Request 

### PR DESCRIPTION
**Pull request by barneyhill**
https://www.barneyhill.net/posts/review/

### CODE REVIEW

**Comment by barneyhill** [comment]
Apologies for the duplicate pull request!

**Comment by discourse-eq** [comment]
This pull request has been mentioned on **Effective Quadratures**. There might be relevant details there:

https://discourse.effective-quadratures.org/t/google-summer-of-code-review-implementing-polynomial-regression-trees-in-effective-quadratures/74/1

**Review by ascillitoe — CHANGES_REQUESTED** [review]
Looks like the `tree_type` and `search_type` need to be updated in the tests.

**Comment by barneyhill** [comment]
Ah missed that! - should be all working now

**Comment by ascillitoe** [comment]
Thanks @barneyhill, looks good now!

**Pull request merged**
