### PR TITLE
Replaced the depracated np.matrix with np.array closes #164

### LINKED ISSUE #164: Convert all instances of np.matrix to np.ndarray
It seems that np.matrix will be deprecated in the future. Thus, all instances of np.matrix should be changed to np.ndarray (e.g. the output of evaluatePolyFit)

In addition, we should stipulate that all 1-d outputs be represented by 1-d arrays instead of "column vectors" with size = (length, 1). It makes working with them more intuitive.

### PR DESCRIPTION
**Pull request by PrayasJ**

### CODE REVIEW

**Comment by psesh** [comment]
HI @PrayasJ, unfortunately your merge request did not pass all the tests. If you need any assistance feel free to reach out. Specifics on which test was failed can be found here: https://travis-ci.org/Effective-Quadratures/Effective-Quadratures/builds/642802270?utm_source=github_status&utm_medium=notification

**Comment by PrayasJ** [comment]
Thanks for the quick reply @pseh.
I was a tad bit confused over how I could run individual tests. 
Running tests.py is time consuming.

**Comment by ascillitoe** [comment]
@psesh can you trigger a travis-ci rebuild? It seems to have stalled...

**Comment by PrayasJ** [comment]
> To maintain a clean codebase can the .txt files be removed from this commit, same for the .vscode directory?
> 
> It might be worth using a local .git/info/exclude to avoid having to add machine specific items to the .gitignore

Yes, I was going to fix that up in the next commit. 
I think there is some very obnoxious thing going on with the enumerate in subsampling.py,
I tried doing a local test and it basically went on for a really really long time, I had to force stop it.

**Comment by psesh** [comment]
Hi @PrayasJ to run a single test file, you can try
`python test.py tests/test_basis.py` 
in the main directory. Hope this helps!

**Comment by PrayasJ** [comment]
@psesh I think there seems to be an issue in the 30th test, can you look into it?
Screenshot (368)

**Comment by psesh** [comment]
Hi @PrayasJ can you commit your latest code, then I can take a look. Cheers!

**Comment by PrayasJ** [comment]
> Hi @PrayasJ can you commit your latest code please, then I can take a look. Cheers!

Thanks for the help, commit made.

**Comment by psesh** [comment]
Hi @hz324 you may need to take a look at this...

**Comment by kritika12298** [comment]
Hello, I am Kritika Gupta and am looking forward to contribute to the project Quadratures for GSOC 2020. Kindly guide me on how to get started.

**Comment by psesh** [comment]
@kritika12298, please have a look at our [Discourse site](https://discourse.effective-quadratures.org/t/google-summer-of-code-2020-projects/31/2) on this topic.

**Pull request closed without merging**
